[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
shuffle_protocol = "3tZMV8JhXCaVz4p8q4xgLU7RefdP438AmohAjjMWL8wH"

[programs.localnet]
shuffle_protocol = "3tZMV8JhXCaVz4p8q4xgLU7RefdP438AmohAjjMWL8wH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 120000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
