[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
shuffle_protocol = "J5B3CHigkr6Tiz9iRACMNk355uY5wFpVCq6847urV3Et"

[programs.localnet]
shuffle_protocol = "DQ29rUToHVTyp2QxP3C7nt1MuYp6p6PKYNaDpGooPAFq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 120000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
